### ISSUE TITLE
GH API Rate limiting preventing label updates

### ISSUE THREAD

**Issue by thermokarst** [qiime2/template-repo#13]
**Bug Description**
We are DOSing the GitHub API when updating issue labels

**Steps to reproduce the behavior**
1. Check out [busywork](https://busywork.qiime2.org/teams/main/pipelines/github-management/jobs/sync-labels/builds/6)

**Screenshots**
![screen shot 2018-11-21 at 7 28 28 am](https://user-images.githubusercontent.com/274668/48847597-2ef0a900-ed5f-11e8-9062-1873b99d1229.png)

**Comment by ebolyen** [comment]
Fixed in https://github.com/qiime2/template-repo/commit/ea360bdd5506035cf70b3b9ca64a50aa4651347a
